packages:
  - apps/*
  - libs/*

allowBuilds:
  esbuild: true

catalog:
  "@types/node": ^26.2.0
  tsdown: ^0.22.14
  typescript: 7.0.2

catalogs:
  oxc:
    oxfmt: ^0.63.0
    oxlint: ^1.78.0
    oxlint-tsgolint: ^7.0.2001
